In [1]:
import cudf
import pandas as pd
import numpy as np

# Example

In [2]:
pdf = pd.DataFrame(np.random.randn(100000000,5))

In [3]:
gdf = cudf.DataFrame.from_pandas(pdf)

In [4]:
results = []
for col in pdf.columns:
    results.append(pdf[col].mean())

In [5]:
results = []
for col in gdf.columns:
    results.append(gdf[col].mean())

In [6]:
4190/12

349.1666666666667

# Reading Data

In [63]:
gdf = cudf.read_csv('US_Accidents_May19.csv')

In [11]:
pdf = pd.read_csv('US_Accidents_May19.csv')

In [12]:
gdf = cudf.DataFrame.from_pandas(pdf)

In [13]:
pdf = gdf.to_pandas()

In [27]:
gdf.describe()

,TMC,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Number,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
count,1.727177e+06,2.243939e+06,2.243939e+06,2.243939e+06,516762.000000,516762.000000,2.243939e+06,785537.000000,2.181674e+06,391569.000000,2.179472e+06,2.186659e+06,2.172579e+06,1.800985e+06,264473.000000
mean,2.073527e+02,2.382692e+00,3.646348e+01,-9.485567e+01,37.443109,-96.527543,2.879090e-01,5625.281008,6.123244e+01,26.042067,6.592758e+01,3.003747e+01,9.124096e+00,8.844042e+00,0.060439
std,1.940527e+01,5.488030e-01,4.958759e+00,1.709453e+01,5.126585,17.986406,1.532341e+00,11071.872897,1.914616e+01,13.478333,2.243013e+01,2.267240e-01,2.986359e+00,4.973200e+00,0.439698
min,2.000000e+02,0.000000e+00,2.457022e+01,-1.246238e+02,24.570110,-124.497829,0.000000e+00,1.000000,-7.780000e+01,-65.900000,4.000000e+00,0.000000e+00,0.000000e+00,1.200000e+00,0.000000
25%,2.010000e+02,2.000000e+00,3.348468e+01,-1.171362e+02,33.887450,-117.870577,0.000000e+00,803.000000,4.890000e+01,19.200000,5.000000e+01,2.992000e+01,1.000000e+01,5.800000e+00,0.000000
50%,2.010000e+02,2.000000e+00,3.586428e+01,-8.818469e+01,38.038480,-90.192310,0.000000e+00,2672.000000,6.300000e+01,28.700000,6.800000e+01,3.003000e+01,1.000000e+01,8.100000e+00,0.010000
75%,2.010000e+02,3.000000e+00,4.042111e+01,-8.085453e+01,41.393320,-80.895040,1.000000e-02,6846.000000,7.590000e+01,36.400000,8.500000e+01,3.015000e+01,1.000000e+01,1.150000e+01,0.040000
max,4.060000e+02,4.000000e+00,4.900076e+01,-6.711317e+01,49.075000,-67.109242,3.336300e+02,961052.000000,1.706000e+02,45.200000,1.000000e+02,3.304000e+01,1.400000e+02,8.228000e+02,10.800000

In [28]:
pdf.describe()

,TMC,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Number,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
count,1.727177e+06,2.243939e+06,2.243939e+06,2.243939e+06,516762.000000,516762.000000,2.243939e+06,785537.000000,2.181674e+06,391569.000000,2.179472e+06,2.186659e+06,2.172579e+06,1.800985e+06,264473.000000
mean,2.073527e+02,2.382692e+00,3.646348e+01,-9.485567e+01,37.443109,-96.527543,2.879095e-01,5625.281008,6.123244e+01,26.042067,6.592758e+01,3.003747e+01,9.124096e+00,8.844042e+00,0.060439
std,1.940527e+01,5.488029e-01,4.958759e+00,1.709453e+01,5.126585,17.986406,1.532341e+00,11071.872897,1.914616e+01,13.478333,2.243013e+01,2.267242e-01,2.986359e+00,4.973200e+00,0.439698
min,2.000000e+02,0.000000e+00,2.457022e+01,-1.246238e+02,24.570110,-124.497829,0.000000e+00,1.000000,-7.780000e+01,-65.900000,4.000000e+00,0.000000e+00,0.000000e+00,1.200000e+00,0.000000
25%,2.010000e+02,2.000000e+00,3.348468e+01,-1.171362e+02,33.887450,-117.870577,0.000000e+00,803.000000,4.890000e+01,19.200000,5.000000e+01,2.992000e+01,1.000000e+01,5.800000e+00,0.000000
50%,2.010000e+02,2.000000e+00,3.586428e+01,-8.818469e+01,38.038480,-90.192310,0.000000e+00,2672.000000,6.300000e+01,28.700000,6.800000e+01,3.003000e+01,1.000000e+01,8.100000e+00,0.010000
75%,2.010000e+02,3.000000e+00,4.042111e+01,-8.085453e+01,41.393320,-80.895040,1.000000e-02,6846.000000,7.590000e+01,36.400000,8.500000e+01,3.015000e+01,1.000000e+01,1.150000e+01,0.040000
max,4.060000e+02,4.000000e+00,4.900076e+01,-6.711317e+01,49.075000,-67.109242,3.336300e+02,961052.000000,1.706000e+02,45.200000,1.000000e+02,3.304000e+01,1.400000e+02,8.228000e+02,10.800000

In [55]:
print(gdf['TMC'].mean())
# no of rows in dataframe
print(len(gdf))
# Shape of Dataframe
print(gdf.shape)

207.35274265463238
2243939
(2243939, 49)

In [40]:
pdf['TMC'].mean()

207.35274265463238

In [42]:
# Handling Columns

In [64]:
columnnames = gdf.columns

In [65]:
columnnames

Index(['ID', 'Source', 'TMC', 'Severity', 'Start_Time', 'End_Time',
       'Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)',
       'Description', 'Number', 'Street', 'Side', 'City', 'County', 'State',
       'Zipcode', 'Country', 'Timezone', 'Airport_Code', 'Weather_Timestamp',
       'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)',
       'Visibility(mi)', 'Wind_Direction', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [66]:
gdf.columns = ['ID', 'Source', 'TMC', 'Severity', 'Start_Time', 'End_Time',
       'Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng', 'Distance_mi',
       'Description', 'Number', 'Street', 'Side', 'City', 'County', 'State',
       'Zipcode', 'Country', 'Timezone', 'Airport_Code', 'Weather_Timestamp',
       'Temperature_F', 'Wind_Chill_F', 'Humidity_%', 'Pressure_in',
       'Visibility_mi', 'Wind_Direction', 'Wind_Speed_mph',
       'Precipitation_in', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight']

In [69]:
gdf = gdf[['ID', 'Source', 'TMC', 'Severity', 'Start_Time', 'End_Time',
       'Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng']]

In [68]:
gdf.head()

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,null,null,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,null,null,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,null,null,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,201.0,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,null,null,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,201.0,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,null,null,...,False,False,False,False,True,False,Day,Day,Day,Day
5,A-6,MapQuest,201.0,3,2016-02-08 07:44:26,2016-02-08 08:14:26,40.100590,-82.925194,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
6,A-7,MapQuest,201.0,2,2016-02-08 07:59:35,2016-02-08 08:29:35,39.758274,-84.230507,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
7,A-8,MapQuest,201.0,3,2016-02-08 07:59:58,2016-02-08 08:29:58,39.770382,-84.194901,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
8,A-9,MapQuest,201.0,2,2016-02-08 08:00:40,2016-02-08 08:30:40,39.778061,-84.172005,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
9,A-10,MapQuest,201.0,3,2016-02-08 08:10:04,2016-02-08 08:40:04,40.100590,-82.925194,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
10,A-11,MapQuest,201.0,3,2016-02-08 08:14:42,2016-02-08 08:44:42,39.952812,-83.119293,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
11,A-12,MapQuest,241.0,3,2016-02-08 08:21:27,2016-02-08 08:51:27,39.932709,-82.830910,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
12,A-13,MapQuest,201.0,2,2016-02-08 08:36:34,2016-02-08 09:06:34,39.737633,-84.149933,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
13,A-14,MapQuest,201.0,2,2016-02-08 08:37:07,2016-02-08 09:07:07,39.790760,-84.241547,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
14,A-15,MapQuest,201.0,2,2016-02-08 08:39:43,2016-02-08 09:09:43,39.972038,-82.913521,null,null,...,False,False,False,False,True,False,Day,Day,Day,Day
15,A-16,MapQuest,201.0,2,2016-02-08 08:43:20,2016-02-08 09:13:20,39.745888,-84.170410,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
16,A-17,MapQuest,201.0,2,2016-02-08 08:53:17,2016-02-08 09:23:17,39.748329,-84.224007,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
17,A-18,MapQuest,201.0,2,2016-02-08 09:24:37,2016-02-08 09:54:37,39.752174,-84.239952,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
18,A-19,MapQuest,201.0,2,2016-02-08 09:25:17,2016-02-08 09:55:17,39.740669,-84.184135,null,null,...,False,False,False,False,True,False,Day,Day,Day,Day
19,A-20,MapQuest,201.0,2,2016-02-08 09:35:35,2016-02-08 10:05:35,39.790703,-84.244461,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
20,A-21,MapQuest,201.0,2,2016-02-08 10:11:15,2016-02-08 10:41:15,40.052509,-82.882332,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
21,A-22,MapQuest,201.0,2,2016-02-08 10:24:27,2016-02-08 10:54:27,39.773346,-84.224686,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
22,A-23,MapQuest,201.0,2,2016-02-08 11:53:19,2016-02-08 12:23:19,39.628288,-84.226151,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
23,A-24,MapQuest,201.0,3,2016-02-08 12:00:00,2016-02-08 12:45:00,40.023487,-82.994888,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
24,A-25,MapQuest,201.0,2,2016-02-08 12:16:44,2016-02-08 13:01:44,39.761379,-84.259216,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
25,A-26,MapQuest,201.0,2,2016-02-08 12:41:08,2016-02-08 13:11:08,40.158024,-82.641762,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
26,A-27,MapQuest,201.0,2,2016-02-08 12:52:05,2016-02-08 13:37:05,39.733219,-84.159653,null,null,...,False,False,False,False,True,False,Day,Day,Day,Day
27,A-28,MapQuest,201.0,2,2016-02-08 14:24:48,2016-02-08 15:09:48,39.775303,-84.200523,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
28,A-29,MapQuest,201.0,2,2016-02-08 14:56:57,2016-02-08 15:41:57,39.789322,-84.239105,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
29,A-30,MapQuest,201.0,2,2016-02-08 15:26:14,2016-02-08 16:11:14,39.758720,-84.183762,null,null,...,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2243909,A-2243910,Bing,null,2,2017-08-30 16:21:55,2017-08-30 22:21:55,33.778710,-117.895060,33.7789,-117.88104,...,False,False,False,False,False,False,Day,Day,Day,Day
2243910,A-2243911,Bing,null,2,2017-08-30 16:24:55,2017-08-30 22:24:55,34.136180,-117.442180,34.1362,-117.435962,...,False,False,False,False,False,False,Day,Day,Day,Day
2243911,A-2243912,Bing,null,2,2017-08-30 16:33:55,2017-08-30 22:33:55,34.036850,-118.287120,34.03737,-118.28231,...,False,False,False,False,False,False,Day,Day,Day,Day
2243912,A-2243913,Bing,null,2,2017-08-30 16:45:10,2017-08-30 22:45:10,36.515580,-121.439030,36.51129,-121.43674,...,False,False,False,False,False,False,Day,Day,Day,Day
2243913,A-2243914,Bing,null,2,2017-08-30 16:52:40,2017-08-30 22:52:40,33.859790,-118.036120,33.8654,-118.04847,...,False,False,False,False,False,False,Day,Day,Day,Day
2243914,A-2243915,Bing,null,2,2017-08-30 16:50:25,2017-08-30 22:50:25,33.803770,-117.880056,33.792482,-117.879559,...,False,False,False,False,False,False,Day,Day,Day,Day
2243915,A-2243916,Bing,null,2,2017-08-30 16:54:10,2017-08-30 22:54:10,34.103750,-117.983520,34.11787,-117.97369,...,False,False,False,False,False,False,Day,Day,Day,Day
2243916,A-2243917,Bing,null,3,2017-08-30 16:56:25,2017-08-30 22:56:25,33.865330,-118.048740,33.86079,-118.03902,...,False,False,False,False,False,False,Day,Day,Day,Day
2243917,A-2243918,Bing,null,3,2017-08-30 17:00:10,2017-08-30 23:00:10,32.835170,-117.233900,32.83345,-117.23315,...,False,False,False,False,False,False,Day,Day,Day,Day
2243918,A-2243919,Bing,null,3,2017-08-30 17:00:10,2017-08-30 23:00:10,32.839592,-117.236971,32.837544,-117.234029,...,False,False,False,False,False,False,Day,Day,Day,Day
2243919,A-2243920,Bing,null,2,2017-08-30 17:22:40,2017-08-30 23:22:40,33.841450,-118.286130,33.84405,-118.28466,...,False,False,False,False,False,False,Day,Day,Day,Day
2243920,A-2243921,Bing,null,2,2017-08-30 17:27:10,2017-08-30 23:27:10,32.649470,-117.063810,32.66554,-117.07961,...,False,False,False,False,False,False,Day,Day,Day,Day
2243921,A-2243922,Bing,null,2,2017-08-30 17:28:40,2017-08-30 23:28:40,32.673913,-117.083141,32.65416,-117.07086,...,False,False,False,False,False,False,Day,Day,Day,Day
2243922,A-2243923,Bing,null,2,2017-08-30 17:30:10,2017-08-30 23:30:10,36.748189,-119.776100,36.75981,-119.7753,...,False,False,False,False,False,False,Day,Day,Day,Day
2243923,A-2243924,Bing,null,2,2017-08-30 17:35:25,2017-08-30 23:35:25,35.287398,-120.662498,35.29099,-120.65773,...,False,False,False,False,False,False,Day,Day,Day,Day
2243924,A-2243925,Bing,null,2,2017-08-30 17:42:55,2017-08-30 23:42:55,35.100277,-120.117394,35.084546,-120.145096,...,False,False,False,False,False,False,Day,Day,Day,Day
2243925,A-2243926,Bing,null,2,2017-08-30 17:46:40,2017-08-30 23:46:40,34.119240,-118.150310,34.11914,-118.15289,...,False,False,False,False,True,False,Day,Day,Day,Day
2243926,A-2243927,Bing,null,3,2017-08-30 17:49:40,2017-08-30 23:49:40,34.156890,-118.379250,34.15104,-118.37492,...,False,False,False,False,False,False,Day,Day,Day,Day
2243927,A-2243928,Bing,null,2,2017-08-30 18:27:55,2017-08-31 00:27:55,34.135560,-117.987510,34.13556,-117.99076,...,False,False,False,False,False,False,Day,Day,Day,Day
2243928,A-2243929,Bing,null,2,2017-08-30 18:24:10,2017-08-31 00:24:10,33.856080,-118.024690,33.85979,-118.03612,...,False,False,False,False,False,False,Day,Day,Day,Day
2243929,A-2243930,Bing,null,2,2017-08-30 18:25:40,2017-08-31 00:25:40,33.664060,-117.800770,33.66272,-117.79116,...,False,False,False,False,False,False,Day,Day,Day,Day
2243930,A-2243931,Bing,null,3,2017-08-30 19:02:25,2017-08-31 01:02:25,33.611830,-117.704020,33.628939,-117.720919,...,False,False,False,False,False,False,Day,Day,Day,Day
2243931,A-2243932,Bing,null,2,2017-08-30 19:03:55,2017-08-31 01:03:55,33.735680,-117.819310,33.73096,-117.81197,...,False,False,False,False,False,False,Day,Day,Day,Day
2243932,A-2243933,Bing,null,2,2017-08-30 19:45:10,2017-08-31 01:45:10,33.869047,-117.753330,33.87081,-117.74039,...,False,False,False,False,False,False,Night,Night,Day,Day
2243933,A-2243934,Bing,null,3,2017-08-30 19:48:10,2017-08-31 01:48:10,34.123370,-118.341790,34.12942,-118.34751,...,False,False,False,False,False,False,Night,Night,Day,Day
2243934,A-2243935,Bing,null,2,2017-08-30 20:01:40,2017-08-31 02:01:40,34.055160,-118.214070,34.05822,-118.21427,...,False,False,False,False,False,False,Night,Night,Day,Day
2243935,A-2243936,Bing,null,2,2017-08-30 20:01:40,2017-08-31 02:01:40,34.046740,-118.214800,34.05516,-118.21407,...,False,False,False,False,False,False,Night,Night,Day,Day
2243936,A-2243937,Bing,null,3,2017-08-30 20:03:10,2017-08-31 02:03:10,34.031850,-117.135910,34.02537,-117.11616,...,False,False,False,False,False,False,Night,Night,Day,Day
2243937,A-2243938,Bing,null,4,2017-08-30 20:49:40,2017-08-31 02:49:40,34.277860,-118.608280,34.266581,-118.640372,...,False,False,False,False,False,False,Night,Night,Night,Night
2243938,A-2243939,Bing,null,4,2017-08-30 20:48:10,2017-08-31 02:48:10,34.324205,-118.502123,34.31079,-118.48667,...,False,False,False,False,False,False,Night,Night,Night,Day

# Apply Lambda

In [224]:
gdf = cudf.read_csv('US_Accidents_May19.csv')
gdf.columns = ['ID', 'Source', 'TMC', 'Severity', 'Start_Time', 'End_Time',
       'Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng', 'Distance_mi',
       'Description', 'Number', 'Street', 'Side', 'City', 'County', 'State',
       'Zipcode', 'Country', 'Timezone', 'Airport_Code', 'Weather_Timestamp',
       'Temperature_F', 'Wind_Chill_F', 'Humidity_%', 'Pressure_in',
       'Visibility_mi', 'Wind_Direction', 'Wind_Speed_mph',
       'Precipitation_in', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight']

In [93]:
pdf['Somecol'] = (pdf['TMC'] + pdf['Severity']/10)/2

In [94]:
gdf['Somecol'] = (gdf['TMC'] + gdf['Severity']/10)/2

In [225]:
def somefunc(x):
    return x+2
gdf['Somecol'] = gdf['TMC'].applymap(somefunc)

In [131]:
gdf.tail()

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Somecol
2243934,A-2243935,Bing,null,2,2017-08-30 20:01:40,2017-08-31 02:01:40,34.055160,-118.214070,34.058220,-118.214270,...,False,False,False,False,False,Night,Night,Day,Day,null
2243935,A-2243936,Bing,null,2,2017-08-30 20:01:40,2017-08-31 02:01:40,34.046740,-118.214800,34.055160,-118.214070,...,False,False,False,False,False,Night,Night,Day,Day,null
2243936,A-2243937,Bing,null,3,2017-08-30 20:03:10,2017-08-31 02:03:10,34.031850,-117.135910,34.025370,-117.116160,...,False,False,False,False,False,Night,Night,Day,Day,null
2243937,A-2243938,Bing,null,4,2017-08-30 20:49:40,2017-08-31 02:49:40,34.277860,-118.608280,34.266581,-118.640372,...,False,False,False,False,False,Night,Night,Night,Night,null
2243938,A-2243939,Bing,null,4,2017-08-30 20:48:10,2017-08-31 02:48:10,34.324205,-118.502123,34.310790,-118.486670,...,False,False,False,False,False,Night,Night,Night,Day,null

In [115]:
from math import cos, sin, asin, sqrt, pi
def haversine_distance(lat1, lon1, lat2, lon2):
    """Haversine distance formula taken from Michael Dunn's StackOverflow post:
    https://stackoverflow.com/questions/4913349/haversine-formula-in-python-bearing-and-distance-between-two-gps-points
    """
    x_1 = pi/180 * lat1
    y_1 = pi/180 * lon1
    x_2 = pi/180 * lat2
    y_2 = pi/180 * lon2

    dlon = y_2 - y_1
    dlat = x_2 - x_1
    a = sin(dlat/2)**2 + cos(x_1) * cos(x_2) * sin(dlon/2)**2

    c = 2 * asin(sqrt(a)) 
    r = 6371 # Radius of earth in kilometers

    return c * r

        
pdf['hDistance'] = pdf.apply(lambda x: haversine_distance(x['Start_Lat'],x['Start_Lng'],x['End_Lat'],x['End_Lng']),axis=1)

In [151]:
def haversine_distance_kernel(lat1, lon1, lat2, lon2, hDistance):
    """Haversine distance formula taken from Michael Dunn's StackOverflow post:
    https://stackoverflow.com/questions/4913349/haversine-formula-in-python-bearing-and-distance-between-two-gps-points
    """
    for i, (x_1, y_1, x_2, y_2) in enumerate(zip(lat1, lon1, lat2, lon2)):
        x_1 = pi/180 * x_1
        y_1 = pi/180 * y_1
        x_2 = pi/180 * x_2
        y_2 = pi/180 * y_2

        dlon = y_2 - y_1
        dlat = x_2 - x_1
        a = sin(dlat/2)**2 + cos(x_1) * cos(x_2) * sin(dlon/2)**2

        c = 2 * asin(sqrt(a)) 
        r = 6371 # Radius of earth in kilometers

        hDistance[i] = c * r

gdf = gdf.apply_rows(haversine_distance_kernel,
                    incols = {'Start_Lat':'lat1','Start_Lng':'lon1','End_Lat':'lat2','End_Lng':'lon2'},
                                  outcols = dict(hDistance=np.float64),
                                  kwargs=dict())

# Filtering

In [168]:
df_dis_gt_2 = gdf[gdf['hDistance']>2]

In [170]:
And_df = gdf[(gdf['hDistance']>8) & (gdf['TMC']>200)]

In [171]:
Or_df = gdf[(gdf['hDistance']>8) | (gdf['TMC']>200)]

In [172]:
Not_df = gdf[~((gdf['hDistance']>8) | (gdf['TMC']>200))]

#  Groupby

In [203]:
gdf.groupby(['Traffic_Calming','Sunrise_Sunset']).agg({'TMC':'mean','Severity':'mean'}).reset_index()

   Traffic_Calming Sunrise_Sunset         TMC  Severity
0            False            Day  207.054248  2.356019
1            False          Night  208.200609  2.456571
2             True            Day  205.236585  2.145969
3             True          Night  205.614815  2.125786

In [204]:
gdf.groupby(['Traffic_Calming','Sunrise_Sunset']).agg({'TMC':'mean','Severity':'mean'}).reset_index()

   Traffic_Calming Sunrise_Sunset         TMC  Severity
0            False            Day  207.054248  2.356019
1            False          Night  208.200609  2.456571
2             True            Day  205.236585  2.145969
3             True          Night  205.614815  2.125786

# Merge and Concat

In [206]:
severity_lt_3 = gdf[gdf['Severity']<3]
severity_gte_3 = gdf[gdf['Severity']>=3]

In [208]:
fullseverity = cudf.concat([severity_lt_3,severity_gte_3])

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,out,hDistance
1,A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,null,null,...,False,False,False,False,Night,Night,Night,Day,null,null
2,A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,null,null,...,False,False,True,False,Night,Night,Day,Day,null,null
4,A-5,MapQuest,201.0,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,null,null,...,False,False,True,False,Day,Day,Day,Day,null,null
6,A-7,MapQuest,201.0,2,2016-02-08 07:59:35,2016-02-08 08:29:35,39.758274,-84.230507,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
8,A-9,MapQuest,201.0,2,2016-02-08 08:00:40,2016-02-08 08:30:40,39.778061,-84.172005,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
12,A-13,MapQuest,201.0,2,2016-02-08 08:36:34,2016-02-08 09:06:34,39.737633,-84.149933,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
13,A-14,MapQuest,201.0,2,2016-02-08 08:37:07,2016-02-08 09:07:07,39.790760,-84.241547,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
14,A-15,MapQuest,201.0,2,2016-02-08 08:39:43,2016-02-08 09:09:43,39.972038,-82.913521,null,null,...,False,False,True,False,Day,Day,Day,Day,null,null
15,A-16,MapQuest,201.0,2,2016-02-08 08:43:20,2016-02-08 09:13:20,39.745888,-84.170410,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
16,A-17,MapQuest,201.0,2,2016-02-08 08:53:17,2016-02-08 09:23:17,39.748329,-84.224007,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
17,A-18,MapQuest,201.0,2,2016-02-08 09:24:37,2016-02-08 09:54:37,39.752174,-84.239952,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
18,A-19,MapQuest,201.0,2,2016-02-08 09:25:17,2016-02-08 09:55:17,39.740669,-84.184135,null,null,...,False,False,True,False,Day,Day,Day,Day,null,null
19,A-20,MapQuest,201.0,2,2016-02-08 09:35:35,2016-02-08 10:05:35,39.790703,-84.244461,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
20,A-21,MapQuest,201.0,2,2016-02-08 10:11:15,2016-02-08 10:41:15,40.052509,-82.882332,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
21,A-22,MapQuest,201.0,2,2016-02-08 10:24:27,2016-02-08 10:54:27,39.773346,-84.224686,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
22,A-23,MapQuest,201.0,2,2016-02-08 11:53:19,2016-02-08 12:23:19,39.628288,-84.226151,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
24,A-25,MapQuest,201.0,2,2016-02-08 12:16:44,2016-02-08 13:01:44,39.761379,-84.259216,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
25,A-26,MapQuest,201.0,2,2016-02-08 12:41:08,2016-02-08 13:11:08,40.158024,-82.641762,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
26,A-27,MapQuest,201.0,2,2016-02-08 12:52:05,2016-02-08 13:37:05,39.733219,-84.159653,null,null,...,False,False,True,False,Day,Day,Day,Day,null,null
27,A-28,MapQuest,201.0,2,2016-02-08 14:24:48,2016-02-08 15:09:48,39.775303,-84.200523,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
28,A-29,MapQuest,201.0,2,2016-02-08 14:56:57,2016-02-08 15:41:57,39.789322,-84.239105,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
29,A-30,MapQuest,201.0,2,2016-02-08 15:26:14,2016-02-08 16:11:14,39.758720,-84.183762,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
30,A-31,MapQuest,201.0,2,2016-02-08 16:16:08,2016-02-08 16:46:08,40.081459,-83.122398,null,null,...,False,False,True,False,Day,Day,Day,Day,null,null
31,A-32,MapQuest,201.0,2,2016-02-08 17:39:24,2016-02-08 18:24:24,39.833210,-84.112946,null,null,...,False,False,False,False,Day,Day,Day,Day,null,null
34,A-35,MapQuest,201.0,2,2016-02-08 20:22:38,2016-02-08 21:07:38,39.994766,-83.024490,null,null,...,False,False,False,False,Night,Night,Night,Night,null,null
35,A-36,MapQuest,201.0,2,2016-02-08 20:43:00,2016-02-08 23:00:00,40.006477,-83.030991,null,null,...,False,False,False,False,Night,Night,Night,Night,null,null
36,A-37,MapQuest,201.0,2,2016-02-09 04:28:48,2016-02-09 04:58:48,39.742062,-84.186996,null,null,...,False,False,False,False,Night,Night,Night,Night,null,null
37,A-38,MapQuest,201.0,2,2016-02-09 05:04:34,2016-02-09 05:34:34,39.843521,-82.781570,null,null,...,False,False,False,False,Night,Night,Night,Night,null,null
38,A-39,MapQuest,201.0,2,2016-02-09 05:17:08,2016-02-09 05:47:08,39.782578,-84.178688,null,null,...,False,False,False,False,Night,Night,Night,Night,null,null
40,A-41,MapQuest,201.0,2,2016-02-09 05:40:57,2016-02-09 06:10:57,39.447502,-84.191208,null,null,...,False,False,False,False,Night,Night,Night,Night,null,null
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2243782,A-2243783,Bing,null,4,2017-08-29 23:35:25,2017-08-30 05:35:25,47.139807,-122.094998,47.14077,-122.09155,...,False,False,False,False,Night,Night,Night,Night,0.281918735,0.281918735
2243785,A-2243786,Bing,null,3,2017-08-30 06:26:25,2017-08-30 12:26:25,47.425772,-122.279199,47.424431,-122.281259,...,False,False,False,False,Day,Day,Day,Day,0.215060325,0.215060325
2243802,A-2243803,Bing,null,3,2017-08-30 10:21:10,2017-08-30 16:21:10,38.322842,-122.025739,38.29315,-122.03427,...,False,False,False,False,Day,Day,Day,Day,3.384469322,3.384469322
2243804,A-2243805,Bing,null,3,2017-08-30 10:32:25,2017-08-30 16:32:25,37.834648,-122.294874,37.83735,-122.29622,...,False,False,False,False,Day,Day,Day,Day,0.322864518,0.322864518
2243837,A-2243838,Bing,null,4,2017-08-30 16:34:40,2017-08-30 22:34:40,41.097870,-122.344820,41.09364,-122.34648,...,False,False,False,False,Day,Day,Day,Day,0.49049305,0.49049305
2243843,A-2243844,Bing,null,3,2017-08-30 17:22:40,2017-08-30 23:22:40,37.316410,-121.956180,37.3167,-121.95004,...,False,False,False,False,Day,Day,Day,Day,0.54393618,0.54393618
2243852,A-2243853,Bing,null,4,2017-08-30 00:20:25,2017-08-30 06:20:25,35.380882,-120.632554,35.370572,-120.64131,...,False,False,False,False,Night,Night,Night,Night,1.394453693,1.394453693
2243854,A-2243855,Bing,null,3,2017-08-30 03:08:25,2017-08-30 09:08:25,34.053597,-118.004550,34.054737,-118.003922,...,False,False,False,False,Night,Night,Night,Night,0.139340846,0.139340846
2243856,A-2243857,Bing,null,3,2017-08-30 04:04:40,2017-08-30 10:04:40,35.370187,-120.641011,35.380967,-120.632169,...,False,False,False,False,Night,Night,Night,Night,1.442048178,1.442048178
2243857,A-2243858,Bing,null,3,2017-08-30 04:04:40,2017-08-30 10:04:40,35.380882,-120.632554,35.370572,-120.64131,...,False,False,False,False,Night,Night,Night,Night,1.394453693,1.394453693
2243863,A-2243864,Bing,null,3,2017-08-30 07:21:10,2017-08-30 13:21:10,33.655800,-117.759070,33.6481,-117.76214,...,False,False,False,False,Day,Day,Day,Day,0.902124083,0.902124083
2243864,A-2243865,Bing,null,3,2017-08-30 07:23:25,2017-08-30 13:23:25,33.860560,-118.313430,33.85981,-118.30961,...,False,False,False,False,Day,Day,Day,Day,0.362449204,0.362449204
2243868,A-2243869,Bing,null,3,2017-08-30 08:25:40,2017-08-30 14:25:40,32.673971,-117.082928,32.68015,-117.086,...,False,False,False,False,Day,Day,Day,Day,0.744809541,0.744809541
2243869,A-2243870,Bing,null,3,2017-08-30 08:51:10,2017-08-30 14:51:10,34.344290,-118.504950,34.3384,-118.50737,...,False,False,False,False,Day,Day,Day,Day,0.691600232,0.691600232
2243870,A-2243871,Bing,null,3,2017-08-30 08:52:40,2017-08-30 14:52:40,34.030290,-117.701990,34.03011,-117.7116,...,False,False,False,False,Day,Day,Day,Day,0.885806729,0.885806729
2243875,A-2243876,Bing,null,3,2017-08-30 10:33:10,2017-08-30 16:33:10,34.134370,-118.356260,34.143517,-118.367429,...,False,False,False,False,Day,Day,Day,Day,1.446070985,1.446070985
2243876,A-2243877,Bing,null,3,2017-08-30 11:00:10,2017-08-30 17:00:10,33.875330,-118.104430,33.87806,-118.103,...,False,False,False,False,Day,Day,Day,Day,0.331025696,0.331025696
2243877,A-2243878,Bing,null,3,2017-08-30 11:00:10,2017-08-30 17:00:10,34.048210,-118.265970,34.05025,-118.26262,...,False,False,False,False,Day,Day,Day,Day,0.383032511,0.383032511
2243880,A-2243881,Bing,null,3,2017-08-30 11:56:25,2017-08-30 17:56:25,34.160850,-118.470930,34.15717,-118.46935,...,False,False,False,False,Day,Day,Day,Day,0.434255029,0.434255029
2243881,A-2243882,Bing,null,3,2017-08-30 11:56:25,2017-08-30 17:56:25,34.156110,-118.468920,34.15575,-118.46866,...,False,False,False,False,Day,Day,Day,Day,0.046634434,0.046634434
2243882,A-2243883,Bing,null,3,2017-08-30 11:56:25,2017-08-30 17:56:25,34.162900,-118.472120,34.16085,-118.47093,...,False,False,False,False,Day,Day,Day,Day,0.252881723,0.252881723
2243916,A-2243917,Bing,null,3,2017-08-30 16:56:25,2017-08-30 22:56:25,33.865330,-118.048740,33.86079,-118.03902,...,False,False,False,False,Day,Day,Day,Day,1.029715926,1.029715926
2243917,A-2243918,Bing,null,3,2017-08-30 17:00:10,2017-08-30 23:00:10,32.835170,-117.233900,32.83345,-117.23315,...,False,False,False,False,Day,Day,Day,Day,0.203688006,0.203688006
2243918,A-2243919,Bing,null,3,2017-08-30 17:00:10,2017-08-30 23:00:10,32.839592,-117.236971,32.837544,-117.234029,...,False,False,False,False,Day,Day,Day,Day,0.356942003,0.356942003
2243926,A-2243927,Bing,null,3,2017-08-30 17:49:40,2017-08-30 23:49:40,34.156890,-118.379250,34.15104,-118.37492,...,False,False,False,False,Day,Day,Day,Day,0.762815974,0.762815974
2243930,A-2243931,Bing,null,3,2017-08-30 19:02:25,2017-08-31 01:02:25,33.611830,-117.704020,33.628939,-117.720919,...,False,False,False,False,Day,Day,Day,Day,2.463274875,2.463274875
2243933,A-2243934,Bing,null,3,2017-08-30 19:48:10,2017-08-31 01:48:10,34.123370,-118.341790,34.12942,-118.34751,...,False,False,False,False,Night,Night,Day,Day,0.854270779,0.854270779
2243936,A-2243937,Bing,null,3,2017-08-30 20:03:10,2017-08-31 02:03:10,34.031850,-117.135910,34.02537,-117.11616,...,False,False,False,False,Night,Night,Day,Day,1.957476113,1.957476113
2243937,A-2243938,Bing,null,4,2017-08-30 20:49:40,2017-08-31 02:49:40,34.277860,-118.608280,34.266581,-118.640372,...,False,False,False,False,Night,Night,Night,Night,3.204501086,3.204501086
2243938,A-2243939,Bing,null,4,2017-08-30 20:48:10,2017-08-31 02:48:10,34.324205,-118.502123,34.31079,-118.48667,...,False,False,False,False,Night,Night,Night,Day,2.05893054,2.05893054

In [218]:
accident_times_dataframe = gdf[['ID','Start_Time','End_Time']]
accident_locations_dataframe = gdf[['ID','Start_Lat','Start_Lng','End_Lat','End_Lng']]

In [219]:
accident_times_dataframe.head()

    ID           Start_Time             End_Time
0  A-1  2016-02-08 05:46:00  2016-02-08 11:00:00
1  A-2  2016-02-08 06:07:59  2016-02-08 06:37:59
2  A-3  2016-02-08 06:49:27  2016-02-08 07:19:27
3  A-4  2016-02-08 07:23:34  2016-02-08 07:53:34
4  A-5  2016-02-08 07:39:07  2016-02-08 08:09:07

In [220]:
accident_locations_dataframe.head()

    ID  Start_Lat  Start_Lng End_Lat End_Lng
0  A-1  39.865147 -84.058723    null    null
1  A-2  39.928059 -82.831184    null    null
2  A-3  39.063148 -84.032608    null    null
3  A-4  39.747753 -84.205582    null    null
4  A-5  39.627781 -84.188354    null    null

In [221]:
pd_accident_times_dataframe = pdf[['ID','Start_Time','End_Time']]
pd_accident_locations_dataframe = pdf[['ID','Start_Lat','Start_Lng','End_Lat','End_Lng']]

In [222]:
information_df = cudf.merge(accident_times_dataframe,accident_locations_dataframe,on='ID',how='inner')

In [223]:
pd_information_df = pd.merge(pd_accident_times_dataframe,pd_accident_locations_dataframe,on='ID',how='inner')